version: "3.3"

services:
  zookeeper:
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181/tcp"

  kafka:
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    user: root

  user-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: test123
      POSTGRES_DB: mahoni
    volumes:
      - ./debezium/init:/docker-entrypoint-initdb.d
    command: -p 5432
    ports:
      - "5432:5432/tcp"

  trip-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: test123
      POSTGRES_DB: mahoni
    volumes:
      - ./debezium/init:/docker-entrypoint-initdb.d
    command: -p 5433
    ports:
      - "5433:5433/tcp"

  voucher-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: test123
      POSTGRES_DB: mahoni
    volumes:
      - ./debezium/init:/docker-entrypoint-initdb.d
    command: -p 5434
    ports:
      - "5434:5434/tcp"

  user-service:
    environment:
      SPRING_PROFILES_ACTIVE: docker
    image: zsaschz/user-service:1.0-SNAPSHOT
    depends_on:
      - user-db
    ports:
      - "8080:8080"


  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:5.4.0
    hostname: kafka-schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://kafka-schema-registry:8081
    depends_on:
      - zookeeper
      - kafka

  debezium:
    image: debezium/connect:1.9
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://kafka-schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://kafka-schema-registry:8081
    depends_on:
      - kafka
      - kafka-schema-registry
    ports:
      - "8083:8083"

  # Utility
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: PLAINTEXT://kafka:29092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://kafka-schema-registry:8081/

  jobmanager:
    image: flink:latest
    hostname: jobmanager
    ports:
      - "8050:8081"
    command: jobmanager
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager"
    volumes:
      - ./job/artifacts:/home

  taskmanager:
    image: flink:latest
    hostname: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    deploy:
      replicas: 2
    volumes:
      - ./job/artifacts:/home
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
