/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mahoni.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AirQualityTableSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4925249226817139925L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AirQualityTableSchema\",\"namespace\":\"com.mahoni.schema\",\"fields\":[{\"name\":\"sensorId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"aqi\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AirQualityTableSchema> ENCODER =
      new BinaryMessageEncoder<AirQualityTableSchema>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AirQualityTableSchema> DECODER =
      new BinaryMessageDecoder<AirQualityTableSchema>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AirQualityTableSchema> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AirQualityTableSchema> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AirQualityTableSchema> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AirQualityTableSchema>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AirQualityTableSchema to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AirQualityTableSchema from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AirQualityTableSchema instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AirQualityTableSchema fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String sensorId;
   private double aqi;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AirQualityTableSchema() {}

  /**
   * All-args constructor.
   * @param sensorId The new value for sensorId
   * @param aqi The new value for aqi
   */
  public AirQualityTableSchema(java.lang.String sensorId, java.lang.Double aqi) {
    this.sensorId = sensorId;
    this.aqi = aqi;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sensorId;
    case 1: return aqi;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sensorId = value$ != null ? value$.toString() : null; break;
    case 1: aqi = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'sensorId' field.
   * @return The value of the 'sensorId' field.
   */
  public java.lang.String getSensorId() {
    return sensorId;
  }


  /**
   * Sets the value of the 'sensorId' field.
   * @param value the value to set.
   */
  public void setSensorId(java.lang.String value) {
    this.sensorId = value;
  }

  /**
   * Gets the value of the 'aqi' field.
   * @return The value of the 'aqi' field.
   */
  public double getAqi() {
    return aqi;
  }


  /**
   * Sets the value of the 'aqi' field.
   * @param value the value to set.
   */
  public void setAqi(double value) {
    this.aqi = value;
  }

  /**
   * Creates a new AirQualityTableSchema RecordBuilder.
   * @return A new AirQualityTableSchema RecordBuilder
   */
  public static com.mahoni.schema.AirQualityTableSchema.Builder newBuilder() {
    return new com.mahoni.schema.AirQualityTableSchema.Builder();
  }

  /**
   * Creates a new AirQualityTableSchema RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AirQualityTableSchema RecordBuilder
   */
  public static com.mahoni.schema.AirQualityTableSchema.Builder newBuilder(com.mahoni.schema.AirQualityTableSchema.Builder other) {
    if (other == null) {
      return new com.mahoni.schema.AirQualityTableSchema.Builder();
    } else {
      return new com.mahoni.schema.AirQualityTableSchema.Builder(other);
    }
  }

  /**
   * Creates a new AirQualityTableSchema RecordBuilder by copying an existing AirQualityTableSchema instance.
   * @param other The existing instance to copy.
   * @return A new AirQualityTableSchema RecordBuilder
   */
  public static com.mahoni.schema.AirQualityTableSchema.Builder newBuilder(com.mahoni.schema.AirQualityTableSchema other) {
    if (other == null) {
      return new com.mahoni.schema.AirQualityTableSchema.Builder();
    } else {
      return new com.mahoni.schema.AirQualityTableSchema.Builder(other);
    }
  }

  /**
   * RecordBuilder for AirQualityTableSchema instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AirQualityTableSchema>
    implements org.apache.avro.data.RecordBuilder<AirQualityTableSchema> {

    private java.lang.String sensorId;
    private double aqi;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mahoni.schema.AirQualityTableSchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sensorId)) {
        this.sensorId = data().deepCopy(fields()[0].schema(), other.sensorId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.aqi)) {
        this.aqi = data().deepCopy(fields()[1].schema(), other.aqi);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing AirQualityTableSchema instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mahoni.schema.AirQualityTableSchema other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.sensorId)) {
        this.sensorId = data().deepCopy(fields()[0].schema(), other.sensorId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.aqi)) {
        this.aqi = data().deepCopy(fields()[1].schema(), other.aqi);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'sensorId' field.
      * @return The value.
      */
    public java.lang.String getSensorId() {
      return sensorId;
    }


    /**
      * Sets the value of the 'sensorId' field.
      * @param value The value of 'sensorId'.
      * @return This builder.
      */
    public com.mahoni.schema.AirQualityTableSchema.Builder setSensorId(java.lang.String value) {
      validate(fields()[0], value);
      this.sensorId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sensorId' field has been set.
      * @return True if the 'sensorId' field has been set, false otherwise.
      */
    public boolean hasSensorId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sensorId' field.
      * @return This builder.
      */
    public com.mahoni.schema.AirQualityTableSchema.Builder clearSensorId() {
      sensorId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'aqi' field.
      * @return The value.
      */
    public double getAqi() {
      return aqi;
    }


    /**
      * Sets the value of the 'aqi' field.
      * @param value The value of 'aqi'.
      * @return This builder.
      */
    public com.mahoni.schema.AirQualityTableSchema.Builder setAqi(double value) {
      validate(fields()[1], value);
      this.aqi = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'aqi' field has been set.
      * @return True if the 'aqi' field has been set, false otherwise.
      */
    public boolean hasAqi() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'aqi' field.
      * @return This builder.
      */
    public com.mahoni.schema.AirQualityTableSchema.Builder clearAqi() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AirQualityTableSchema build() {
      try {
        AirQualityTableSchema record = new AirQualityTableSchema();
        record.sensorId = fieldSetFlags()[0] ? this.sensorId : (java.lang.String) defaultValue(fields()[0]);
        record.aqi = fieldSetFlags()[1] ? this.aqi : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AirQualityTableSchema>
    WRITER$ = (org.apache.avro.io.DatumWriter<AirQualityTableSchema>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AirQualityTableSchema>
    READER$ = (org.apache.avro.io.DatumReader<AirQualityTableSchema>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.sensorId);

    out.writeDouble(this.aqi);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.sensorId = in.readString();

      this.aqi = in.readDouble();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.sensorId = in.readString();
          break;

        case 1:
          this.aqi = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










