/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mahoni.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UserPointTableSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8173815667571361835L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserPointTableSchema\",\"namespace\":\"com.mahoni.schema\",\"fields\":[{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"point\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserPointTableSchema> ENCODER =
      new BinaryMessageEncoder<UserPointTableSchema>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserPointTableSchema> DECODER =
      new BinaryMessageDecoder<UserPointTableSchema>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserPointTableSchema> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserPointTableSchema> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserPointTableSchema> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UserPointTableSchema>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserPointTableSchema to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserPointTableSchema from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserPointTableSchema instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserPointTableSchema fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String userId;
   private int point;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserPointTableSchema() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param point The new value for point
   */
  public UserPointTableSchema(java.lang.String userId, java.lang.Integer point) {
    this.userId = userId;
    this.point = point;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return point;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = value$ != null ? value$.toString() : null; break;
    case 1: point = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.String getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'point' field.
   * @return The value of the 'point' field.
   */
  public int getPoint() {
    return point;
  }


  /**
   * Sets the value of the 'point' field.
   * @param value the value to set.
   */
  public void setPoint(int value) {
    this.point = value;
  }

  /**
   * Creates a new UserPointTableSchema RecordBuilder.
   * @return A new UserPointTableSchema RecordBuilder
   */
  public static com.mahoni.schema.UserPointTableSchema.Builder newBuilder() {
    return new com.mahoni.schema.UserPointTableSchema.Builder();
  }

  /**
   * Creates a new UserPointTableSchema RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserPointTableSchema RecordBuilder
   */
  public static com.mahoni.schema.UserPointTableSchema.Builder newBuilder(com.mahoni.schema.UserPointTableSchema.Builder other) {
    if (other == null) {
      return new com.mahoni.schema.UserPointTableSchema.Builder();
    } else {
      return new com.mahoni.schema.UserPointTableSchema.Builder(other);
    }
  }

  /**
   * Creates a new UserPointTableSchema RecordBuilder by copying an existing UserPointTableSchema instance.
   * @param other The existing instance to copy.
   * @return A new UserPointTableSchema RecordBuilder
   */
  public static com.mahoni.schema.UserPointTableSchema.Builder newBuilder(com.mahoni.schema.UserPointTableSchema other) {
    if (other == null) {
      return new com.mahoni.schema.UserPointTableSchema.Builder();
    } else {
      return new com.mahoni.schema.UserPointTableSchema.Builder(other);
    }
  }

  /**
   * RecordBuilder for UserPointTableSchema instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserPointTableSchema>
    implements org.apache.avro.data.RecordBuilder<UserPointTableSchema> {

    private java.lang.String userId;
    private int point;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mahoni.schema.UserPointTableSchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.point)) {
        this.point = data().deepCopy(fields()[1].schema(), other.point);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing UserPointTableSchema instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mahoni.schema.UserPointTableSchema other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.point)) {
        this.point = data().deepCopy(fields()[1].schema(), other.point);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.String getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.mahoni.schema.UserPointTableSchema.Builder setUserId(java.lang.String value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.mahoni.schema.UserPointTableSchema.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'point' field.
      * @return The value.
      */
    public int getPoint() {
      return point;
    }


    /**
      * Sets the value of the 'point' field.
      * @param value The value of 'point'.
      * @return This builder.
      */
    public com.mahoni.schema.UserPointTableSchema.Builder setPoint(int value) {
      validate(fields()[1], value);
      this.point = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'point' field has been set.
      * @return True if the 'point' field has been set, false otherwise.
      */
    public boolean hasPoint() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'point' field.
      * @return This builder.
      */
    public com.mahoni.schema.UserPointTableSchema.Builder clearPoint() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserPointTableSchema build() {
      try {
        UserPointTableSchema record = new UserPointTableSchema();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.String) defaultValue(fields()[0]);
        record.point = fieldSetFlags()[1] ? this.point : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserPointTableSchema>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserPointTableSchema>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserPointTableSchema>
    READER$ = (org.apache.avro.io.DatumReader<UserPointTableSchema>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.userId);

    out.writeInt(this.point);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.userId = in.readString();

      this.point = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.userId = in.readString();
          break;

        case 1:
          this.point = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










