/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mahoni.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UserPointSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2848930939302557537L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserPointSchema\",\"namespace\":\"com.mahoni.schema\",\"fields\":[{\"name\":\"eventId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"prevPoint\",\"type\":\"int\"},{\"name\":\"point\",\"type\":\"int\"},{\"name\":\"lastModifiedBy\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserPointSchema> ENCODER =
      new BinaryMessageEncoder<UserPointSchema>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserPointSchema> DECODER =
      new BinaryMessageDecoder<UserPointSchema>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserPointSchema> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserPointSchema> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserPointSchema> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UserPointSchema>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserPointSchema to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserPointSchema from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserPointSchema instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserPointSchema fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String eventId;
   private long timestamp;
   private java.lang.String userId;
   private int prevPoint;
   private int point;
   private java.lang.String lastModifiedBy;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserPointSchema() {}

  /**
   * All-args constructor.
   * @param eventId The new value for eventId
   * @param timestamp The new value for timestamp
   * @param userId The new value for userId
   * @param prevPoint The new value for prevPoint
   * @param point The new value for point
   * @param lastModifiedBy The new value for lastModifiedBy
   */
  public UserPointSchema(java.lang.String eventId, java.lang.Long timestamp, java.lang.String userId, java.lang.Integer prevPoint, java.lang.Integer point, java.lang.String lastModifiedBy) {
    this.eventId = eventId;
    this.timestamp = timestamp;
    this.userId = userId;
    this.prevPoint = prevPoint;
    this.point = point;
    this.lastModifiedBy = lastModifiedBy;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return timestamp;
    case 2: return userId;
    case 3: return prevPoint;
    case 4: return point;
    case 5: return lastModifiedBy;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = value$ != null ? value$.toString() : null; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: userId = value$ != null ? value$.toString() : null; break;
    case 3: prevPoint = (java.lang.Integer)value$; break;
    case 4: point = (java.lang.Integer)value$; break;
    case 5: lastModifiedBy = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.lang.String getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.String value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.String getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'prevPoint' field.
   * @return The value of the 'prevPoint' field.
   */
  public int getPrevPoint() {
    return prevPoint;
  }


  /**
   * Sets the value of the 'prevPoint' field.
   * @param value the value to set.
   */
  public void setPrevPoint(int value) {
    this.prevPoint = value;
  }

  /**
   * Gets the value of the 'point' field.
   * @return The value of the 'point' field.
   */
  public int getPoint() {
    return point;
  }


  /**
   * Sets the value of the 'point' field.
   * @param value the value to set.
   */
  public void setPoint(int value) {
    this.point = value;
  }

  /**
   * Gets the value of the 'lastModifiedBy' field.
   * @return The value of the 'lastModifiedBy' field.
   */
  public java.lang.String getLastModifiedBy() {
    return lastModifiedBy;
  }


  /**
   * Sets the value of the 'lastModifiedBy' field.
   * @param value the value to set.
   */
  public void setLastModifiedBy(java.lang.String value) {
    this.lastModifiedBy = value;
  }

  /**
   * Creates a new UserPointSchema RecordBuilder.
   * @return A new UserPointSchema RecordBuilder
   */
  public static com.mahoni.schema.UserPointSchema.Builder newBuilder() {
    return new com.mahoni.schema.UserPointSchema.Builder();
  }

  /**
   * Creates a new UserPointSchema RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserPointSchema RecordBuilder
   */
  public static com.mahoni.schema.UserPointSchema.Builder newBuilder(com.mahoni.schema.UserPointSchema.Builder other) {
    if (other == null) {
      return new com.mahoni.schema.UserPointSchema.Builder();
    } else {
      return new com.mahoni.schema.UserPointSchema.Builder(other);
    }
  }

  /**
   * Creates a new UserPointSchema RecordBuilder by copying an existing UserPointSchema instance.
   * @param other The existing instance to copy.
   * @return A new UserPointSchema RecordBuilder
   */
  public static com.mahoni.schema.UserPointSchema.Builder newBuilder(com.mahoni.schema.UserPointSchema other) {
    if (other == null) {
      return new com.mahoni.schema.UserPointSchema.Builder();
    } else {
      return new com.mahoni.schema.UserPointSchema.Builder(other);
    }
  }

  /**
   * RecordBuilder for UserPointSchema instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserPointSchema>
    implements org.apache.avro.data.RecordBuilder<UserPointSchema> {

    private java.lang.String eventId;
    private long timestamp;
    private java.lang.String userId;
    private int prevPoint;
    private int point;
    private java.lang.String lastModifiedBy;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mahoni.schema.UserPointSchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.userId)) {
        this.userId = data().deepCopy(fields()[2].schema(), other.userId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.prevPoint)) {
        this.prevPoint = data().deepCopy(fields()[3].schema(), other.prevPoint);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.point)) {
        this.point = data().deepCopy(fields()[4].schema(), other.point);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.lastModifiedBy)) {
        this.lastModifiedBy = data().deepCopy(fields()[5].schema(), other.lastModifiedBy);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing UserPointSchema instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mahoni.schema.UserPointSchema other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userId)) {
        this.userId = data().deepCopy(fields()[2].schema(), other.userId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.prevPoint)) {
        this.prevPoint = data().deepCopy(fields()[3].schema(), other.prevPoint);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.point)) {
        this.point = data().deepCopy(fields()[4].schema(), other.point);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.lastModifiedBy)) {
        this.lastModifiedBy = data().deepCopy(fields()[5].schema(), other.lastModifiedBy);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.lang.String getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.mahoni.schema.UserPointSchema.Builder setEventId(java.lang.String value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public com.mahoni.schema.UserPointSchema.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.mahoni.schema.UserPointSchema.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.mahoni.schema.UserPointSchema.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.String getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.mahoni.schema.UserPointSchema.Builder setUserId(java.lang.String value) {
      validate(fields()[2], value);
      this.userId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.mahoni.schema.UserPointSchema.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'prevPoint' field.
      * @return The value.
      */
    public int getPrevPoint() {
      return prevPoint;
    }


    /**
      * Sets the value of the 'prevPoint' field.
      * @param value The value of 'prevPoint'.
      * @return This builder.
      */
    public com.mahoni.schema.UserPointSchema.Builder setPrevPoint(int value) {
      validate(fields()[3], value);
      this.prevPoint = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'prevPoint' field has been set.
      * @return True if the 'prevPoint' field has been set, false otherwise.
      */
    public boolean hasPrevPoint() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'prevPoint' field.
      * @return This builder.
      */
    public com.mahoni.schema.UserPointSchema.Builder clearPrevPoint() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'point' field.
      * @return The value.
      */
    public int getPoint() {
      return point;
    }


    /**
      * Sets the value of the 'point' field.
      * @param value The value of 'point'.
      * @return This builder.
      */
    public com.mahoni.schema.UserPointSchema.Builder setPoint(int value) {
      validate(fields()[4], value);
      this.point = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'point' field has been set.
      * @return True if the 'point' field has been set, false otherwise.
      */
    public boolean hasPoint() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'point' field.
      * @return This builder.
      */
    public com.mahoni.schema.UserPointSchema.Builder clearPoint() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastModifiedBy' field.
      * @return The value.
      */
    public java.lang.String getLastModifiedBy() {
      return lastModifiedBy;
    }


    /**
      * Sets the value of the 'lastModifiedBy' field.
      * @param value The value of 'lastModifiedBy'.
      * @return This builder.
      */
    public com.mahoni.schema.UserPointSchema.Builder setLastModifiedBy(java.lang.String value) {
      validate(fields()[5], value);
      this.lastModifiedBy = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'lastModifiedBy' field has been set.
      * @return True if the 'lastModifiedBy' field has been set, false otherwise.
      */
    public boolean hasLastModifiedBy() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'lastModifiedBy' field.
      * @return This builder.
      */
    public com.mahoni.schema.UserPointSchema.Builder clearLastModifiedBy() {
      lastModifiedBy = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserPointSchema build() {
      try {
        UserPointSchema record = new UserPointSchema();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.String) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.userId = fieldSetFlags()[2] ? this.userId : (java.lang.String) defaultValue(fields()[2]);
        record.prevPoint = fieldSetFlags()[3] ? this.prevPoint : (java.lang.Integer) defaultValue(fields()[3]);
        record.point = fieldSetFlags()[4] ? this.point : (java.lang.Integer) defaultValue(fields()[4]);
        record.lastModifiedBy = fieldSetFlags()[5] ? this.lastModifiedBy : (java.lang.String) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserPointSchema>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserPointSchema>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserPointSchema>
    READER$ = (org.apache.avro.io.DatumReader<UserPointSchema>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.eventId);

    out.writeLong(this.timestamp);

    out.writeString(this.userId);

    out.writeInt(this.prevPoint);

    out.writeInt(this.point);

    out.writeString(this.lastModifiedBy);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.eventId = in.readString();

      this.timestamp = in.readLong();

      this.userId = in.readString();

      this.prevPoint = in.readInt();

      this.point = in.readInt();

      this.lastModifiedBy = in.readString();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.eventId = in.readString();
          break;

        case 1:
          this.timestamp = in.readLong();
          break;

        case 2:
          this.userId = in.readString();
          break;

        case 3:
          this.prevPoint = in.readInt();
          break;

        case 4:
          this.point = in.readInt();
          break;

        case 5:
          this.lastModifiedBy = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










